services:
  web:
    image: ghcr.io/moktar837-lab/site-optimealone:latest
    environment:
      SITE: "https://optimealone.example.com"
      BACKEND_URL: "http://backend:8000"
      API_BASE: "/api/v1"
    networks:
      - webnet
    restart: unless-stopped

  caddy:
    image: caddy:2
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"
    environment:
      # Pour ACME/Let's Encrypt
      ACME_AGREE: "true"
      EMAIL: "admin@optimealone.example.com"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - webnet
    restart: unless-stopped

networks:
  webnet:

volumes:
  caddy_data:
  caddy_config:

