services:
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nutrition
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/nutrition
      ASYNC_PG_DSN: postgresql://postgres:postgres@db:5432/nutrition
      CORS_ORIGINS: http://localhost:3000,http://127.0.0.1:3000,http://localhost:4321,http://127.0.0.1:4321
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
volumes:
  pgdata: